services:
  postgres:
    restart: always
    image: postgres:15.3-alpine
    shm_size: 1gb
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '40432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default
  hasura:
    restart: always
    image: hasura/graphql-engine:v${HASURA_VERSION}
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/${POSTGRES_DB}'
      HASURA_GRAPHQL_DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/${POSTGRES_DB}'
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_GRAPHQL_SERVER_PORT: 8080
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_LOG_LEVEL: 'info'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'public'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: 'startup, http-log, webhook-log, websocket-log, query-log'
      HASURA_GRAPHQL_DEV_MODE: 'true'
    ports:
      - '${HASURA_GRAPHQL_SERVER_PORT}:8080'
    networks:
      - default
volumes:
  pgdata: {}
networks:
  default:
    name: ${DOCKER_COMPOSE_NETWORK_NAME}
    external: true
